FROM registry.aliyuncs.com/football/nginx:1.10
COPY ./output /usr/share/nginx/html
#COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/* /etc/nginx/

RUN sed -i 's/192.168.1.17:8000/api.c-f.com/g' /usr/share/nginx/html/main.js 
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone
